In [320]:
import pandas as pd

df = pd.read_csv("GDP_raw_data_file.csv", skiprows=4)
df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"3,092,427,932.96","3,276,187,709.50","3,346,623,191.46","2,471,419,181.72","2,880,902,798.92","3,324,034,443.27","3,834,729,616.12","4,265,650,673.00",NaN,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,"24,205,688,712.38","24,958,886,027.46","27,073,233,856.54","31,769,135,008.65","30,279,553,206.64","33,806,176,716.85",...,"978,076,465,866.45","1,020,955,778,298.17","1,018,714,795,912.35","938,607,563,405.09","1,114,144,799,994.21","1,228,967,879,390.01","1,179,359,054,880.45","1,242,693,542,929.85",NaN,NaN
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"18,753,456,497.82","18,053,222,687.41","18,799,444,490.11","19,955,929,052.15","14,259,995,441.08","14,497,243,872.13","17,152,234,636.87",NaN,NaN,NaN
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,"11,904,805,741.68","12,707,719,290.63","13,630,588,814.30","14,468,913,698.05","15,803,564,796.41","16,920,876,929.66",...,"694,051,345,937.23","777,840,323,023.31","1,026,996,211,935.80","963,784,699,293.98","1,026,651,004,045.79","1,063,649,130,876.99","938,238,370,514.20","736,384,961,061.52",NaN,NaN
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"84,376,935,689.34","89,512,794,227.49","80,734,428,592.54","58,852,456,453.88","79,559,543,805.30","131,212,208,930.34","107,167,747,140.13","100,998,916,781.08",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"7,180,768,692.02","7,878,762,812.28","7,899,741,278.75","7,717,143,395.55","9,413,408,574.49","9,354,907,646.30","10,468,224,574.75","11,197,246,322.59",NaN,NaN
262,"Yemen, Rep.",YEM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,"26,842,229,044.58","21,606,160,663.03",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,GDP (current US$),NY.GDP.MKTP.CD,"8,748,596,500.56","9,225,996,309.60","9,813,996,074.40","10,854,195,658.32","11,955,995,217.60","13,068,994,772.40",...,"381,448,814,653.46","405,260,723,892.52","389,330,032,224.27","337,974,655,408.05","419,986,284,375.37","407,596,043,067.89","381,440,724,491.23","401,144,998,373.59",NaN,NaN
264,Zambia,ZMB,GDP (current US$),NY.GDP.MKTP.CD,"698,739,720.78","682,359,727.33","679,279,728.56","704,339,718.55","822,639,671.27","1,061,199,575.94",...,"25,873,601,260.84","26,311,507,273.67","23,308,667,781.23","18,137,764,930.65","22,096,416,932.01","29,163,782,140.49","27,577,956,471.24","25,303,185,342.25",NaN,NaN
265,Zimbabwe,ZWE,GDP (current US$),NY.GDP.MKTP.CD,"1,053,528,036.43","1,097,206,526.43","1,118,172,225.65","1,160,103,724.13","1,217,759,447.00","1,312,105,393.62",...,"51,035,657,370.52","34,141,666,666.67","33,357,695,635.13","31,980,334,561.31","41,287,673,690.08","40,757,561,708.77","35,871,779,680.63","41,539,411,516.44",NaN,NaN

In [321]:
years = [str(year) for year in range(1990, 2025)]
df = df.rename(columns={"Country Name": "country", "Country Code": "code"})
df = df[['country', 'code'] + years]
df['country'] = df['country'].str.strip()
df

,country,code,1990,1991,1992,1993,1994,1995,1996,1997,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,"764,804,469.27","872,067,039.11","958,659,217.88","1,083,240,223.46","1,245,810,055.87","1,320,670,391.06","1,379,888,268.16","1,531,843,575.42",...,"2,962,906,703.91","2,983,637,430.17","3,092,427,932.96","3,276,187,709.50","3,346,623,191.46","2,471,419,181.72","2,880,902,798.92","3,324,034,443.27","3,834,729,616.12","4,265,650,673.00"
1,Africa Eastern and Southern,AFE,"256,383,050,159.49","276,918,502,950.35","241,188,307,967.90","239,981,176,638.05","243,477,534,983.31","273,327,034,187.59","273,427,612,467.25","288,270,699,674.41",...,"910,002,035,578.04","831,868,076,442.43","978,076,465,866.45","1,020,955,778,298.17","1,018,714,795,912.35","938,607,563,405.09","1,114,144,799,994.21","1,228,967,879,390.01","1,179,359,054,880.45","1,242,693,542,929.85"
2,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"19,134,221,644.73","18,116,572,395.08","18,753,456,497.82","18,053,222,687.41","18,799,444,490.11","19,955,929,052.15","14,259,995,441.08","14,497,243,872.13","17,152,234,636.87",NaN
3,Africa Western and Central,AFW,"124,277,825,786.70","130,794,315,519.50","125,449,432,677.39","130,547,124,413.67","135,350,756,019.39","207,843,864,308.61","263,563,556,144.18","276,460,023,661.74",...,"778,022,057,597.45","700,028,168,335.24","694,051,345,937.23","777,840,323,023.31","1,026,996,211,935.80","963,784,699,293.98","1,026,651,004,045.79","1,063,649,130,876.99","938,238,370,514.20","736,384,961,061.52"
4,Angola,AGO,"11,229,515,599.30","10,603,784,541.20","8,307,810,973.59","5,768,720,421.61","4,438,321,017.39","5,538,749,259.95","7,526,421,519.17","7,648,380,195.60",...,"102,543,067,840.73","59,878,249,719.33","84,376,935,689.34","89,512,794,227.49","80,734,428,592.54","58,852,456,453.88","79,559,543,805.30","131,212,208,930.34","107,167,747,140.13","100,998,916,781.08"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"6,295,848,422.72","6,682,677,289.99","7,180,768,692.02","7,878,762,812.28","7,899,741,278.75","7,717,143,395.55","9,413,408,574.49","9,354,907,646.30","10,468,224,574.75","11,197,246,322.59"
262,"Yemen, Rep.",YEM,"12,643,821,568.96","14,665,445,462.11","17,959,367,194.01","21,736,802,664.45","28,019,483,763.53","12,796,345,679.01","6,496,163,615.66","6,838,298,530.55",...,"42,444,490,073.86","31,317,825,274.15","26,842,229,044.58","21,606,160,663.03",NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,"126,048,140,141.87","135,203,698,237.98","146,956,150,986.64","147,194,747,565.75","153,512,712,381.84","171,735,933,897.33","163,234,925,380.56","168,978,057,327.73",...,"346,709,790,458.56","323,585,509,674.48","381,448,814,653.46","405,260,723,892.52","389,330,032,224.27","337,974,655,408.05","419,986,284,375.37","407,596,043,067.89","381,440,724,491.23","401,144,998,373.59"
264,Zambia,ZMB,"3,288,381,797.32","3,376,806,697.12","3,182,810,841.02","3,273,505,343.86","3,656,806,165.79","3,806,983,413.16","3,597,220,962.00","4,303,288,479.71",...,"21,251,216,798.78","20,958,412,538.31","25,873,601,260.84","26,311,507,273.67","23,308,667,781.23","18,137,764,930.65","22,096,416,932.01","29,163,782,140.49","27,577,956,471.24","25,303,185,342.25"
265,Zimbabwe,ZWE,"8,788,301,546.04","8,646,000,000.00","6,755,000,000.00","6,567,250,000.00","6,894,250,000.00","7,115,000,000.00","8,557,500,000.00","8,534,000,000.00",...,"19,973,250,000.00","20,559,250,000.00","51,035,657,370.52","34,141,666,666.67","33,357,695,635.13","31,980,334,561.31","41,287,673,690.08","40,757,561,708.77","35,871,779,680.63","41,539,411,516.44"

In [322]:
df.dtypes

country     object
code        object
1990       float64
1991       float64
1992       float64
1993       float64
1994       float64
1995       float64
1996       float64
1997       float64
1998       float64
1999       float64
2000       float64
2001       float64
2002       float64
2003       float64
2004       float64
2005       float64
2006       float64
2007       float64
2008       float64
2009       float64
2010       float64
2011       float64
2012       float64
2013       float64
2014       float64
2015       float64
2016       float64
2017       float64
2018       float64
2019       float64
2020       float64
2021       float64
2022       float64
2023       float64
2024       float64
dtype: object

In [323]:
df[years].isna().sum()

1990    26
1991    25
1992    24
1993    23
1994    22
1995    19
1996    19
1997    17
1998    16
1999    16
2000    14
2001    13
2002     9
2003     9
2004     9
2005     9
2006     8
2007     8
2008     7
2009     5
2010     5
2011     4
2012     6
2013     6
2014     5
2015     6
2016     7
2017     7
2018     7
2019     7
2020     8
2021     8
2022     9
2023    15
2024    26
dtype: int64

In [324]:
df_clean = df.fillna(0)
df_clean['country'] = df_clean['country'].str.strip().str.upper()
df_clean

,country,code,1990,1991,1992,1993,1994,1995,1996,1997,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,ARUBA,ABW,"764,804,469.27","872,067,039.11","958,659,217.88","1,083,240,223.46","1,245,810,055.87","1,320,670,391.06","1,379,888,268.16","1,531,843,575.42",...,"2,962,906,703.91","2,983,637,430.17","3,092,427,932.96","3,276,187,709.50","3,346,623,191.46","2,471,419,181.72","2,880,902,798.92","3,324,034,443.27","3,834,729,616.12","4,265,650,673.00"
1,AFRICA EASTERN AND SOUTHERN,AFE,"256,383,050,159.49","276,918,502,950.35","241,188,307,967.90","239,981,176,638.05","243,477,534,983.31","273,327,034,187.59","273,427,612,467.25","288,270,699,674.41",...,"910,002,035,578.04","831,868,076,442.43","978,076,465,866.45","1,020,955,778,298.17","1,018,714,795,912.35","938,607,563,405.09","1,114,144,799,994.21","1,228,967,879,390.01","1,179,359,054,880.45","1,242,693,542,929.85"
2,AFGHANISTAN,AFG,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,"19,134,221,644.73","18,116,572,395.08","18,753,456,497.82","18,053,222,687.41","18,799,444,490.11","19,955,929,052.15","14,259,995,441.08","14,497,243,872.13","17,152,234,636.87",0.00
3,AFRICA WESTERN AND CENTRAL,AFW,"124,277,825,786.70","130,794,315,519.50","125,449,432,677.39","130,547,124,413.67","135,350,756,019.39","207,843,864,308.61","263,563,556,144.18","276,460,023,661.74",...,"778,022,057,597.45","700,028,168,335.24","694,051,345,937.23","777,840,323,023.31","1,026,996,211,935.80","963,784,699,293.98","1,026,651,004,045.79","1,063,649,130,876.99","938,238,370,514.20","736,384,961,061.52"
4,ANGOLA,AGO,"11,229,515,599.30","10,603,784,541.20","8,307,810,973.59","5,768,720,421.61","4,438,321,017.39","5,538,749,259.95","7,526,421,519.17","7,648,380,195.60",...,"102,543,067,840.73","59,878,249,719.33","84,376,935,689.34","89,512,794,227.49","80,734,428,592.54","58,852,456,453.88","79,559,543,805.30","131,212,208,930.34","107,167,747,140.13","100,998,916,781.08"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,KOSOVO,XKX,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,"6,295,848,422.72","6,682,677,289.99","7,180,768,692.02","7,878,762,812.28","7,899,741,278.75","7,717,143,395.55","9,413,408,574.49","9,354,907,646.30","10,468,224,574.75","11,197,246,322.59"
262,"YEMEN, REP.",YEM,"12,643,821,568.96","14,665,445,462.11","17,959,367,194.01","21,736,802,664.45","28,019,483,763.53","12,796,345,679.01","6,496,163,615.66","6,838,298,530.55",...,"42,444,490,073.86","31,317,825,274.15","26,842,229,044.58","21,606,160,663.03",0.00,0.00,0.00,0.00,0.00,0.00
263,SOUTH AFRICA,ZAF,"126,048,140,141.87","135,203,698,237.98","146,956,150,986.64","147,194,747,565.75","153,512,712,381.84","171,735,933,897.33","163,234,925,380.56","168,978,057,327.73",...,"346,709,790,458.56","323,585,509,674.48","381,448,814,653.46","405,260,723,892.52","389,330,032,224.27","337,974,655,408.05","419,986,284,375.37","407,596,043,067.89","381,440,724,491.23","401,144,998,373.59"
264,ZAMBIA,ZMB,"3,288,381,797.32","3,376,806,697.12","3,182,810,841.02","3,273,505,343.86","3,656,806,165.79","3,806,983,413.16","3,597,220,962.00","4,303,288,479.71",...,"21,251,216,798.78","20,958,412,538.31","25,873,601,260.84","26,311,507,273.67","23,308,667,781.23","18,137,764,930.65","22,096,416,932.01","29,163,782,140.49","27,577,956,471.24","25,303,185,342.25"
265,ZIMBABWE,ZWE,"8,788,301,546.04","8,646,000,000.00","6,755,000,000.00","6,567,250,000.00","6,894,250,000.00","7,115,000,000.00","8,557,500,000.00","8,534,000,000.00",...,"19,973,250,000.00","20,559,250,000.00","51,035,657,370.52","34,141,666,666.67","33,357,695,635.13","31,980,334,561.31","41,287,673,690.08","40,757,561,708.77","35,871,779,680.63","41,539,411,516.44"

In [325]:
update_codes = [
"AFG","ALB","DZA","AND","AGO","AIA","ATG","ARG","ARM","AUS","AUT","AZE","BHS","BHR","BGD",
"BRB","BLR","BEL","BLZ","BEN","BTN","BOL","BIH","BWA","BRA","VGB","BRN","BGR","BFA","BDI",
"CPV","KHM","CMR","CAN","CAF","TCD","CHL","CHN","COL","COM","COG","COK","CRI","CIV","HRV",
"CUB","CYP","CZE","PRK","COD","DNK","DJI","DMA","DOM","ECU","EGY","SLV","GNQ","ERI","EST","ETH",
"FJI","FIN","FRA","GAB","GMB","GEO","DEU","GHA","GRC","GRD","GTM","GIN","GNB","GUY","HTI","VAT",
"HND","HUN","ISL","IND","IDN","IRN","IRQ","IRL","ISR","ITA","JAM","JPN","JOR","KAZ","KEN","KIR",
"KWT","KGZ","LAO","LVA","LBN","LSO","LBR","LBY","LIE","LTU","LUX","MDG","MWI","MYS","MDV","MLI",
"MLT","MHL","MRT","MUS","MEX","FSM","MCO","MNG","MNE","MSR","MAR","MOZ","MMR","NAM","NRU","NPL",
"NLD","NZL","NIC","NER","NGA","NIU","NOR","OMN","PAK","PLW","PAN","PNG","PRY","PER","PHL","POL",
"PRT","QAT","KOR","MDA","ROU","RUS","RWA","KNA","LCA","VCT","WSM","SMR","STP","SAU","SEN","SRB",
"SYC","SLE","SGP","SVK","SVN","SLB","SOM","ZAF","SSD","ESP","LKA","PSE","SDN","SUR","SWZ","SWE",
"CHE","SYR","TJK","THA","MKD","TLS","TGO","TKL","TON","TTO","TUN","TUR","TKM","TCA","TUV","UGA",
"UKR","ARE","GBR","TZA","USA","URY","UZB","VUT","VEN","VNM","YEM","ZMB","ZWE",
"ABW","ASM","BMU","KOS","VIR","PRI","KOS"
]
df_clean = df_clean[df_clean['code'].isin(update_codes)].reset_index(drop=True)
df_clean

,country,code,1990,1991,1992,1993,1994,1995,1996,1997,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,ARUBA,ABW,"764,804,469.27","872,067,039.11","958,659,217.88","1,083,240,223.46","1,245,810,055.87","1,320,670,391.06","1,379,888,268.16","1,531,843,575.42",...,"2,962,906,703.91","2,983,637,430.17","3,092,427,932.96","3,276,187,709.50","3,346,623,191.46","2,471,419,181.72","2,880,902,798.92","3,324,034,443.27","3,834,729,616.12","4,265,650,673.00"
1,AFGHANISTAN,AFG,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,"19,134,221,644.73","18,116,572,395.08","18,753,456,497.82","18,053,222,687.41","18,799,444,490.11","19,955,929,052.15","14,259,995,441.08","14,497,243,872.13","17,152,234,636.87",0.00
2,ANGOLA,AGO,"11,229,515,599.30","10,603,784,541.20","8,307,810,973.59","5,768,720,421.61","4,438,321,017.39","5,538,749,259.95","7,526,421,519.17","7,648,380,195.60",...,"102,543,067,840.73","59,878,249,719.33","84,376,935,689.34","89,512,794,227.49","80,734,428,592.54","58,852,456,453.88","79,559,543,805.30","131,212,208,930.34","107,167,747,140.13","100,998,916,781.08"
3,ALBANIA,ALB,"2,028,553,750.00","1,099,559,027.78","652,174,990.84","1,185,315,468.46","1,880,950,864.41","2,905,092,798.62","3,234,486,232.04","2,293,666,029.99",...,"11,470,171,826.96","11,988,668,784.66","13,258,268,435.60","15,379,508,329.76","15,585,111,614.04","15,241,458,744.59","18,031,989,573.03","19,017,247,013.88","23,491,242,727.41","27,046,429,296.67"
4,ANDORRA,AND,"1,028,989,692.07","1,106,891,361.54","1,209,992,020.30","1,007,090,269.87","1,017,544,068.84","1,178,745,282.87","1,224,024,139.21","1,180,645,571.86",...,"2,789,882,569.10","2,896,611,878.63","3,000,160,414.64","3,218,418,631.68","3,155,150,255.91","2,891,002,460.29","3,324,648,075.56","3,380,611,694.73","3,785,065,524.85","4,039,842,405.48"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,SAMOA,WSM,"125,766,269.76","125,597,205.42","132,303,041.36","133,122,897.20","221,098,106.51","224,865,731.38","249,907,868.77","285,475,591.90",...,"824,150,498.65","843,924,796.70","884,844,384.46","878,448,433.40","912,950,466.06","868,884,902.95","859,724,936.06","889,554,711.84","1,044,909,500.03","1,175,749,785.65"
197,"YEMEN, REP.",YEM,"12,643,821,568.96","14,665,445,462.11","17,959,367,194.01","21,736,802,664.45","28,019,483,763.53","12,796,345,679.01","6,496,163,615.66","6,838,298,530.55",...,"42,444,490,073.86","31,317,825,274.15","26,842,229,044.58","21,606,160,663.03",0.00,0.00,0.00,0.00,0.00,0.00
198,SOUTH AFRICA,ZAF,"126,048,140,141.87","135,203,698,237.98","146,956,150,986.64","147,194,747,565.75","153,512,712,381.84","171,735,933,897.33","163,234,925,380.56","168,978,057,327.73",...,"346,709,790,458.56","323,585,509,674.48","381,448,814,653.46","405,260,723,892.52","389,330,032,224.27","337,974,655,408.05","419,986,284,375.37","407,596,043,067.89","381,440,724,491.23","401,144,998,373.59"
199,ZAMBIA,ZMB,"3,288,381,797.32","3,376,806,697.12","3,182,810,841.02","3,273,505,343.86","3,656,806,165.79","3,806,983,413.16","3,597,220,962.00","4,303,288,479.71",...,"21,251,216,798.78","20,958,412,538.31","25,873,601,260.84","26,311,507,273.67","23,308,667,781.23","18,137,764,930.65","22,096,416,932.01","29,163,782,140.49","27,577,956,471.24","25,303,185,342.25"
200,ZIMBABWE,ZWE,"8,788,301,546.04","8,646,000,000.00","6,755,000,000.00","6,567,250,000.00","6,894,250,000.00","7,115,000,000.00","8,557,500,000.00","8,534,000,000.00",...,"19,973,250,000.00","20,559,250,000.00","51,035,657,370.52","34,141,666,666.67","33,357,695,635.13","31,980,334,561.31","41,287,673,690.08","40,757,561,708.77","35,871,779,680.63","41,539,411,516.44"

In [326]:
removed_rows = df[~df['country'].isin(df_clean['country'])]
removed_countries = removed_rows['country'].tolist()
removed_countries

['Aruba',
 'Africa Eastern and Southern',
 'Afghanistan',
 'Africa Western and Central',
 'Angola',
 'Albania',
 'Andorra',
 'Arab World',
 'United Arab Emirates',
 'Argentina',
 'Armenia',
 'American Samoa',
 'Antigua and Barbuda',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Burundi',
 'Belgium',
 'Benin',
 'Burkina Faso',
 'Bangladesh',
 'Bulgaria',
 'Bahrain',
 'Bahamas, The',
 'Bosnia and Herzegovina',
 'Belarus',
 'Belize',
 'Bermuda',
 'Bolivia',
 'Brazil',
 'Barbados',
 'Brunei Darussalam',
 'Bhutan',
 'Botswana',
 'Central African Republic',
 'Canada',
 'Central Europe and the Baltics',
 'Switzerland',
 'Channel Islands',
 'Chile',
 'China',
 "Cote d'Ivoire",
 'Cameroon',
 'Congo, Dem. Rep.',
 'Congo, Rep.',
 'Colombia',
 'Comoros',
 'Cabo Verde',
 'Costa Rica',
 'Caribbean small states',
 'Cuba',
 'Curacao',
 'Cayman Islands',
 'Cyprus',
 'Czechia',
 'Germany',
 'Djibouti',
 'Dominica',
 'Denmark',
 'Dominican Republic',
 'Algeria',
 'East Asia & Pacific (excluding high income)',
 'Early-demographic dividend',
 'East Asia & Pacific',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia',
 'Ecuador',
 'Egypt, Arab Rep.',
 'Euro area',
 'Eritrea',
 'Spain',
 'Estonia',
 'Ethiopia',
 'European Union',
 'Fragile and conflict affected situations',
 'Finland',
 'Fiji',
 'France',
 'Faroe Islands',
 'Micronesia, Fed. Sts.',
 'Gabon',
 'United Kingdom',
 'Georgia',
 'Ghana',
 'Gibraltar',
 'Guinea',
 'Gambia, The',
 'Guinea-Bissau',
 'Equatorial Guinea',
 'Greece',
 'Grenada',
 'Greenland',
 'Guatemala',
 'Guam',
 'Guyana',
 'High income',
 'Hong Kong SAR, China',
 'Honduras',
 'Heavily indebted poor countries (HIPC)',
 'Croatia',
 'Haiti',
 'Hungary',
 'IBRD only',
 'IDA & IBRD total',
 'IDA total',
 'IDA blend',
 'Indonesia',
 'IDA only',
 'Isle of Man',
 'India',
 'Not classified',
 'Ireland',
 'Iran, Islamic Rep.',
 'Iraq',
 'Iceland',
 'Israel',
 'Italy',
 'Jamaica',
 'Jordan',
 'Japan',
 'Kazakhstan',
 'Kenya',
 'Kyrgyz Republic',
 'Cambodia',
 'Kiribati',
 'St. Kitts and Nevis',
 'Korea, Rep.',
 'Kuwait',
 'Latin America & Caribbean (excluding high income)',
 'Lao PDR',
 'Lebanon',
 'Liberia',
 'Libya',
 'St. Lucia',
 'Latin America & Caribbean',
 'Least developed countries: UN classification',
 'Low income',
 'Liechtenstein',
 'Sri Lanka',
 'Lower middle income',
 'Low & middle income',
 'Lesotho',
 'Late-demographic dividend',
 'Lithuania',
 'Luxembourg',
 'Latvia',
 'Macao SAR, China',
 'St. Martin (French part)',
 'Morocco',
 'Monaco',
 'Moldova',
 'Madagascar',
 'Maldives',
 'Middle East, North Africa, Afghanistan & Pakistan',
 'Mexico',
 'Marshall Islands',
 'Middle income',
 'North Macedonia',
 'Mali',
 'Malta',
 'Myanmar',
 'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)',
 'Montenegro',
 'Mongolia',
 'Northern Mariana Islands',
 'Mozambique',
 'Mauritania',
 'Mauritius',
 'Malawi',
 'Malaysia',
 'North America',
 'Namibia',
 'New Caledonia',
 'Niger',
 'Nigeria',
 'Nicaragua',
 'Netherlands',
 'Norway',
 'Nepal',
 'Nauru',
 'New Zealand',
 'OECD members',
 'Oman',
 'Other small states',
 'Pakistan',
 'Panama',
 'Peru',
 'Philippines',
 'Palau',
 'Papua New Guinea',
 'Poland',
 'Pre-demographic dividend',
 'Puerto Rico (US)',
 "Korea, Dem. People's Rep.",
 'Portugal',
 'Paraguay',
 'West Bank and Gaza',
 'Pacific island small states',
 'Post-demographic dividend',
 'French Polynesia',
 'Qatar',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'South Asia',
 'Saudi Arabia',
 'Sudan',
 'Senegal',
 'Singapore',
 'Solomon Islands',
 'Sierra Leone',
 'El Salvador',
 'San Marino',
 'Somalia, Fed. Rep.',
 'Serbia',
 'Sub-Saharan Africa (excluding high income)',
 'South Sudan',
 'Sub-Saharan Africa',
 'Small states',
 'Sao Tome and Principe',
 'Suriname',
 'Slovak Republic',
 'Slovenia',
 'Sweden',
 'Eswatini',
 'Sint Maarten (Dutch part)',
 'Seychelles',
 'Syrian Arab Republic',
 'Turks and Caicos Islands',
 'Chad',
 'East Asia & Pacific (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Togo',
 'Thailand',
 'Tajikistan',
 'Turkmenistan',
 'Latin America & the Caribbean (IDA & IBRD countries)',
 'Timor-Leste',
 'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)',
 'Tonga',
 'South Asia (IDA & IBRD)',
 'Sub-Saharan Africa (IDA & IBRD countries)',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkiye',
 'Tuvalu',
 'Tanzania',
 'Uganda',
 'Ukraine',
 'Upper middle income',
 'Uruguay',
 'United States',
 'Uzbekistan',
 'St. Vincent and the Grenadines',
 'Venezuela, RB',
 'British Virgin Islands',
 'Virgin Islands (U.S.)',
 'Viet Nam',
 'Vanuatu',
 'World',
 'Samoa',
 'Kosovo',
 'Yemen, Rep.',
 'South Africa',
 'Zambia',
 'Zimbabwe']

In [327]:
df_clean[['country','2024']].sort_values(by='2024', ascending=False).head(10)

            country                  2024
188   UNITED STATES 28,750,956,130,731.20
35            CHINA 18,743,803,170,827.20
47          GERMANY  4,685,592,577,804.69
89            JAPAN  4,027,597,523,550.58
80            INDIA  3,909,891,533,858.08
64   UNITED KINGDOM  3,686,033,044,482.13
61           FRANCE  3,160,442,622,465.08
86            ITALY  2,380,825,077,243.59
32           CANADA  2,243,636,826,633.76
26           BRAZIL  2,185,821,648,943.86

In [328]:
print(df_clean.duplicated(subset=['country', 'code']).sum())

0

In [329]:
df_clean.to_csv("GDP_cleaned_data.csv", index=False)